# Desire Lines for four boroughs of NYC
The Bronx, Brooklyn, Manhattan, Queens

Depends on `ggmap` and `tidyverse`. 

```{r}
library(ggmap)
library(tidyverse)
```

Set the value of the google maps key
```{r}
register_google(Sys.getenv("GOOGLE_MAPS_API_KEY", "standard"))
```

Disable Scientific Notation
```{r}
options(scipen = 999)
```

Import data
```{r}
od <- read.csv("./data/nyc_od_cw_tract_coord.csv")
```

Create data that excludes trips to Manhattan for work
```{r}
exclude_manhattan_work_od <- od %>%
  filter(w_geocode_county != 61)
```

Set the base map 
```{r}
nyc_map <- get_map(location = "New York, NY", zoom = 11, color = "bw")
```

Map all of the desire lines
```{r, out.width = "100%", fig.align = "center", echo=FALSE}
ggmap(nyc_map, darken = 0.8) +
  geom_segment(
    data = od[od$S000 > 4,],
    aes(y = h_lat, x = h_lon, yend = w_lat, xend = w_lon, alpha = S000),
    color = "white",
    size = 0.3
  ) +
  scale_alpha_continuous(range = c(0.004, 0.3)) +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
  )
```

Map the desire lines that exclude manhattan as the working location
```{r, out.width = "100%", fig.align = "center", echo=FALSE}
ggmap(nyc_map, darken = 0.8) +
  geom_segment(
    data = exclude_manhattan_work_od[exclude_manhattan_work_od$S000 > 4,],
    aes(y = h_lat, x = h_lon, yend = w_lat, xend = w_lon, alpha = S000),
    color = "white",
    size = 0.3
  ) +
  scale_alpha_continuous(range = c(0.004, 0.3)) +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
  )
```

